travis:
  secure:
    BINSTAR_TOKEN: b4qkJo/4OkWQHmRpRwJljtA734zAV13thl+YmYK7ljVhwxsM3Br3CY9qjrUGxdKsLm7JPpcODwWO3kk9vaf3KnEOCV1bhqiUlP0zJaHOhvopC7Kjnqd00UrpomHLAWR4nmhxCPpiOWIfdsrDMpGJwtYsEBli6Rgj7lM9bLow9vB8qNroLhr9jSjXpCMZoSaj9cpxyPhVmrivWecrPvBi5VSJQoMFJH/lToJMfR5JwiEtqyhU3nfL11dNPXfSFWcp6OzrK28oNOObUMILC1pE2GR+yIjYTf9pAEooxzOPDFBs5ID3pzbXSfelFQfMhwQwLJnRnOa8HKoiak8tnK4/FDbrRZnniEfnRf+JNUc/twx8rdXfZUlubpePgybfWAorTqOxLT+hi2pJRZWtJ2H4eU1+/7aDuqZrI/1px8BKdaWX1ziQLw+pipbsuyldauYOVN8VhfanVvxjsWy+T45jaRXeYl0/Lmcjer1+cxsjN6RSGc9DiIUJAPE3my9TyW9jNbvV474fwqstdr6amwUVAwtX/K3DYjg1KJNGNdw4TaRkCdQ/cnYV/Gs0oeVZcKfiAWi4JcK1lpGU7MdHx5MJS4H7bW7ScK7k3bNUHKThTrXEZWWN2kGcCp8UUhZmxgDZlJ1zKb1jVAOrBnKuMDIp/FUkWljnNYlUy/wxBbDQSTE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
